version: '3.7'

services:
  main:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - 3001:3001
    networks:
      - nesjs-network
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  mongodb:
    image : mongo:latest
    container_name: mongodb
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    networks:
      - nesjs-network
    restart: always

networks:
  nesjs-network:
